[package]
name = "dht11rs"
version = "0.1.0"
edition = "2021"


[dependencies]

chrono = "0.4"

dht-mmap-rust = "0.1"

rusqlite = "0.25"

serde = { version = "1.0", features = ["derive"] }

serde_json = "1.0"
